<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ConanLegacyDoctor</AssemblyName>
    <RootNamespace>ConanLegacyDoctor.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>embedded</DebugType>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConanLegacyDoctor.Core\ConanLegacyDoctor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\AppIcon.png" />
    <Resource Include="Assets\BranchSwitchToEnhanced.png" />
    <Resource Include="Assets\BranchSwitchToLegacy.png" />
    <Resource Include="Assets\UninstallConanExiles.png" />
  </ItemGroup>
</Project>
